import Nav from '@/components/Nav';

export const metadata = {
  title: "Transportes X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="holder">
            <div className="logo">
              <img src="/images/logo.png" width="100"
                   alt="Transportes X" />
              <h1>Transportes </h1>
            </div>
          </div>
        </header>
        <Nav />

        {children}

        <footer>
          <p>Derechos reservados. Transportes X Año 2026</p>
        </footer>

      </body>
    </html>
  );
}