export const metadata = {
    title: "Transportes x :: Nosotros",
    description: " destacadosGenerated by create next app",
};

export default function Nosotros() {

    return (
        <section className="holder">
            <div className="historia">
                <h2>Historia </h2>
                <div>
                    <p>Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Praesentium, ut aperiam
                        suscipit, ad asperiores quia, sint porro </p>

                    <p>Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Praesentium, ut aperiam
                        suscipit, ad asperiores quia, sint porro </p>
                </div>
                <h2>Staff</h2>
                <div className="personas">
                    <div className="persona" >
                        <img src="https://fakeimg.pl/120x120" width="75"
                            alt="imagen1" />
                        <h5>Juan Gomez</h5>
                        <h6>Gerente General</h6>
                        <p>Lorem, ipsum dolor sit amet consectetur
                            adipisicing elit. Minus incidunt culpa consectetur nisi quis
                            sapiente asperiores eos </p>
                    </div>
                </div>
                 <div className="personas">
                    <div className="persona" >
                        <img src="https://fakeimg.pl/120x120" width="75"
                            alt="imagen1" />
                        <h5>Juan Gomez</h5>
                        <h6>Gerente General</h6>
                        <p>Lorem, ipsum dolor sit amet consectetur
                            adipisicing elit. Minus incidunt culpa consectetur nisi quis
                            sapiente asperiores eos </p>
                    </div>
                </div>
                 <div className="personas">
                    <div className="persona" >
                        <img src="https://fakeimg.pl/120x120" width="75"
                            alt="imagen1" />
                        <h5>Juan Gomez</h5>
                        <h6>Gerente General</h6>
                        <p>Lorem, ipsum dolor sit amet consectetur
                            adipisicing elit. Minus incidunt culpa consectetur nisi quis
                            sapiente asperiores eos </p>
                    </div>
                </div>
                 <div className="personas">
                    <div className="persona" >
                        <img src="https://fakeimg.pl/120x120" width="75"
                            alt="imagen1" />
                        <h5>Juan Gomez</h5>
                        <h6>Gerente General</h6>
                        <p>Lorem, ipsum dolor sit amet consectetur
                            adipisicing elit. Minus incidunt culpa consectetur nisi quis
                            sapiente asperiores eos </p>
                    </div>
                </div>
                 <div className="personas">
                    <div className="persona" >
                        <img src="https://fakeimg.pl/120x120" width="75"
                            alt="imagen1" />
                        <h5>Juan Gomez</h5>
                        <h6>Gerente General</h6>
                        <p>Lorem, ipsum dolor sit amet consectetur
                            adipisicing elit. Minus incidunt culpa consectetur nisi quis
                            sapiente asperiores eos </p>
                    </div>
                </div>
            </div>
        </section>
    )
}