import NovedadItem from "@/components/";

export const metadata = {
    title: "Transportes X :: Novedades",
    description: " destacadosGenerated by create next app",
};

export default function Novedades() {

    return (
        <section className="holder">
            <h2>Novedades</h2>
            {/* vamos a traer el componente de novedadItem */}
        </section>
    )
}
